language: c

before_install:
  - sudo apt-get install gcc-arm-linux-gnueabihf
  - sudo apt-get install qemu-user

script:
  - make clean
  - make

compiler:
  - clang
  - gcc

os:
  - linux
  - osx


